<#
.SYNOPSIS
    Watches the BambuFarm stack from outside and restarts whatever has stopped answering.

.DESCRIPTION
    Every alert this app sends is generated BY the app, so a crashed or wedged container is completely
    silent - you find out because prints stopped, hours later. This runs outside the stack and watches it
    from the other side.

    Two kinds of check, because they fail differently:

      1. Container state (docker inspect). Catches an exit, a crash loop, a container that never came back
         after a host reboot.
      2. An HTTP probe of https://localhost:8081/. Catches the failure state 1 cannot see: a container that
         is "running" while the JVM inside it is wedged on a deadlock or thrashing the heap.

    bambuweb publishes no ports of its own - nginx proxies it - so the probe necessarily goes through nginx,
    and the response tells us which one is broken:

      * a normal page (2xx/3xx/4xx)  -> both are fine; the login redirect counts, we are testing that it
                                        serves, not that it authenticates
      * 502 / 503 / 504             -> nginx is alive and bambuweb is not answering it -> restart bambuweb
      * nothing at all              -> nginx is down (or the host networking is) -> restart nginx

    Restarts only after CONSECUTIVE failures (default 3). A single missed probe is usually a slow poll or a
    long GC pause, and restarting on one would interrupt prints for nothing. A restart is not free: it drops
    in-memory state (AI check history, dispatch backoff) and, if it lands as a print finishes, the outcome of
    that job can end up unknowable.

    It also declines to restart while a printer is actively printing unless -Force is given - see
    -IgnorePrinting.

.PARAMETER Failures
    Consecutive failed probes before acting. Default 3. At the suggested 5-minute schedule that is a
    ~15-minute outage before intervention.

.PARAMETER IgnorePrinting
    Restart even if the data folder suggests a print is in progress. Off by default: a wedged UI is annoying,
    but a restart mid-print can lose the job's accounting.

.PARAMETER WhatIf
    Probe and log, but never restart. Good for the first few days.

.EXAMPLE
    .\heartbeat.ps1 -WhatIf
    One probe, no action. Confirms the URL and service names are right for your setup.

.EXAMPLE
    schtasks /create /tn "BambuFarm heartbeat" /sc minute /mo 5 /ru "$env:USERNAME" /rl HIGHEST /tr `
        "powershell.exe -NoProfile -ExecutionPolicy Bypass -File C:\Users\Vishal\Desktop\BambuFarm_Project\heartbeat.ps1"
    Register it to run every 5 minutes. Run this line from an elevated prompt. Task Scheduler must run it as
    a user in the docker-users group, or docker commands will fail.
#>
[CmdletBinding()]
param(
    # Empty by default - resolved by Resolve-ProdPath, which validates rather than assumes. A watchdog
    # pointed at the wrong folder reports a perfectly healthy farm that isn't the one you are running.
    [string]$ProdPath,
    [string]$Url        = 'https://localhost:8081/',
    [string]$AppService = 'bambuweb',
    [string]$WebService = 'nginx',
    [int]$Failures      = 3,
    [int]$TimeoutSec    = 25,
    [switch]$IgnorePrinting,
    [switch]$WhatIf
)

. "$PSScriptRoot\bambufarm-common.ps1"

# Native tools here (docker) signal failure through exit codes and chatter on stderr. Letting either become a
# terminating error is how the earlier scripts in this repo died, so: check $LASTEXITCODE explicitly instead.
$ErrorActionPreference = 'Continue'
if (Test-Path variable:PSNativeCommandUseErrorActionPreference) {
    $PSNativeCommandUseErrorActionPreference = $false
}

try {
    $ProdPath = Resolve-ProdPath -Explicit $ProdPath
} catch {
    Write-Host "FATAL: $($_.Exception.Message)"
    exit 2
}

# Derived AFTER the resolve, or the state file and log land next to a path that was never validated.
$stateFile = Join-Path $ProdPath 'heartbeat-state.json'
$logFile   = Join-Path $ProdPath 'heartbeat.log'

function Write-Log {
    param([string]$Text, [switch]$Warn)
    $line = '{0}  {1}' -f (Get-Date -Format 'yyyy-MM-dd HH:mm:ss'), $Text
    if ($Warn) { Write-Host $line -ForegroundColor Yellow } else { Write-Host $line }
    try { Add-Content -LiteralPath $logFile -Value $line -ErrorAction Stop } catch { }
}

# --------------------------------------------------------------------------------------------------
# container state
# --------------------------------------------------------------------------------------------------
# 'docker compose ps --format' has meant different things across Compose v2 releases (Go template in some,
# only table/json in others). 'ps -q' has been stable throughout, so resolve the id there and ask docker
# inspect - which has always taken a Go template - for the status.
function Get-ContainerStatus {
    param([string]$Service)
    Push-Location -LiteralPath $ProdPath
    try {
        $id = (docker compose ps -q $Service 2>$null | Where-Object { $_ } | Select-Object -First 1)
        if ($LASTEXITCODE -ne 0 -or -not $id) { return 'absent' }
        $status = (docker inspect -f '{{.State.Status}}' $id 2>$null | Select-Object -First 1)
        if ($LASTEXITCODE -ne 0 -or -not $status) { return 'absent' }
        return $status.Trim()
    } finally {
        Pop-Location
    }
}

function Restart-Service2 {
    param([string]$Service)
    Push-Location -LiteralPath $ProdPath
    try {
        docker compose restart $Service
        if ($LASTEXITCODE -ne 0) {
            # 'restart' only works on a container that still exists; one that was removed, or never created
            # after a host reboot, needs 'up'.
            Write-Log "  'restart $Service' exited $LASTEXITCODE - trying 'up -d'"
            docker compose up -d $Service
        }
    } finally {
        Pop-Location
    }
}

# --------------------------------------------------------------------------------------------------
# http probe
# --------------------------------------------------------------------------------------------------
# Returns the status code, or 0 when nothing answered at all. The cert is self-signed, so validation is off:
# this probe is asking "is it serving", not "is it trustworthy", and it only ever talks to localhost.
function Get-ProbeStatus {
    $params = @{
        Uri             = $Url
        TimeoutSec      = $TimeoutSec
        UseBasicParsing = $true
        ErrorAction     = 'Stop'
    }
    if ($PSVersionTable.PSVersion.Major -ge 6) {
        $params['SkipCertificateCheck'] = $true
        $params['SkipHttpErrorCheck']   = $true
    } else {
        # Windows PowerShell 5.1 has neither switch: trust-all via the global callback, and read the code
        # off the exception for non-2xx.
        [System.Net.ServicePointManager]::ServerCertificateValidationCallback = { $true }
        [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12
    }
    try {
        $r = Invoke-WebRequest @params
        return [int]$r.StatusCode
    } catch {
        $resp = $_.Exception.Response
        if ($resp -and $resp.StatusCode) { return [int]$resp.StatusCode }
        return 0   # refused, timed out, DNS - nothing is listening
    }
}

# --------------------------------------------------------------------------------------------------
# is a print running?
# --------------------------------------------------------------------------------------------------
# Best-effort and deliberately conservative: if we cannot tell, we assume something IS printing and hold off.
# The app writes its running-job state under data/; a file touched in the last few minutes means the app was
# alive recently and had work. This is a guard against restarting mid-print, not a source of truth.
function Test-PrintLikelyRunning {
    $dataDir = Join-Path $ProdPath 'data'
    if (-not (Test-Path -LiteralPath $dataDir)) { return $false }
    $recent = Get-ChildItem -LiteralPath $dataDir -Filter '*.json' -File -ErrorAction SilentlyContinue |
              Where-Object { $_.Name -match 'job|print|queue|history' -and
                             $_.LastWriteTime -gt (Get-Date).AddMinutes(-10) }
    return [bool]$recent
}

# --------------------------------------------------------------------------------------------------
# probe
# --------------------------------------------------------------------------------------------------
$appState = Get-ContainerStatus $AppService
$webState = Get-ContainerStatus $WebService
$code     = Get-ProbeStatus

$appRunning = $appState -eq 'running'
$webRunning = $webState -eq 'running'
$served     = $code -ge 200 -and $code -lt 500          # 5xx is nginx reporting a dead upstream
$healthy    = $appRunning -and $webRunning -and $served

# Which service to act on. Order matters: a container that is not running is a harder fact than a status code.
$target = $null
$why    = ''
if (-not $webRunning)      { $target = $WebService; $why = "$WebService is '$webState'" }
elseif (-not $appRunning)  { $target = $AppService; $why = "$AppService is '$appState'" }
elseif ($code -eq 0)       { $target = $WebService; $why = 'nothing answered on the port' }
elseif (-not $served)      { $target = $AppService; $why = "nginx returned $code - upstream not answering" }

# --------------------------------------------------------------------------------------------------
# consecutive-failure counter
# --------------------------------------------------------------------------------------------------
$count = 0
$restartsToday = 0
$lastRestart = [datetime]::MinValue
if (Test-Path -LiteralPath $stateFile) {
    try {
        $s = Get-Content -LiteralPath $stateFile -Raw -ErrorAction Stop | ConvertFrom-Json
        $count         = [int]$s.count
        $restartsToday = [int]$s.restartsToday
        if ($s.lastRestart) { $lastRestart = [datetime]$s.lastRestart }
    } catch { }
}
# Roll the daily counter over at midnight.
if ($lastRestart.Date -ne (Get-Date).Date) { $restartsToday = 0 }

function Save-State {
    param([int]$Count, [int]$RestartsToday, [datetime]$LastRestart)
    $obj = [pscustomobject]@{
        count         = $Count
        restartsToday = $RestartsToday
        lastRestart   = $LastRestart.ToString('o')
        updated       = (Get-Date).ToString('o')
    }
    try { $obj | ConvertTo-Json | Set-Content -LiteralPath $stateFile -Encoding UTF8 -ErrorAction Stop } catch { }
}

if ($healthy) {
    if ($count -gt 0) { Write-Log "recovered - healthy again after $count failed probe(s)" }
    Save-State 0 $restartsToday $lastRestart
    exit 0
}

$count++
Write-Log ("UNHEALTHY {0}/{1} - {2}={3} {4}={5} http={6} :: {7}" -f `
           $count, $Failures, $AppService, $appState, $WebService, $webState,
           $(if ($code) { $code } else { 'no answer' }), $why) -Warn

if ($count -lt $Failures) {
    Save-State $count $restartsToday $lastRestart
    exit 1
}

# --------------------------------------------------------------------------------------------------
# act
# --------------------------------------------------------------------------------------------------
# A restart loop is worse than being down: it can churn a print queue for hours. Past this many in a day,
# stop and leave it for a human - the log will say why.
if ($restartsToday -ge 6) {
    Write-Log "restart budget spent ($restartsToday today) - NOT restarting. Something needs a human." -Warn
    Save-State $count $restartsToday $lastRestart
    exit 2
}

if (-not $IgnorePrinting -and $target -eq $AppService -and (Test-PrintLikelyRunning)) {
    Write-Log "would restart $AppService, but the data folder suggests a print is in progress - holding off. Use -IgnorePrinting to override." -Warn
    Save-State $count $restartsToday $lastRestart
    exit 1
}

if ($WhatIf) {
    Write-Log "WHATIF: would restart '$target' now ($why)"
    Save-State $count $restartsToday $lastRestart
    exit 1
}

Write-Log "RESTARTING '$target' after $count consecutive failures ($why)" -Warn
Restart-Service2 $target
$restartsToday++
$lastRestart = Get-Date

# Confirm rather than assume. Quarkus + Vaadin takes a while to come up, so give it a real chance before
# calling it a failure; polling means a fast start is not punished by a fixed sleep.
$deadline = (Get-Date).AddSeconds(120)
do {
    Start-Sleep -Seconds 10
    $code2  = Get-ProbeStatus
    $state2 = Get-ContainerStatus $target
} while ($code2 -eq 0 -and (Get-Date) -lt $deadline)

if ($state2 -eq 'running' -and $code2 -ge 200 -and $code2 -lt 500) {
    Write-Log "back up - '$target' is running and the site answered $code2"
    Save-State 0 $restartsToday $lastRestart
    exit 0
}

Write-Log "STILL UNHEALTHY after restarting '$target' - container='$state2' http=$(if ($code2) { $code2 } else { 'no answer' }). Needs a human." -Warn
Save-State $count $restartsToday $lastRestart
exit 2
